import re

with open(r'C:\Users\ethan\.openclaw\workspace\builds\washu-navigator\backend\main.py', 'r', encoding='utf-8') as f:
    content = f.read()

# The new tree_retrieve function as a plain string
new_func = (
    'def tree_retrieve(query: str, tree: dict, model: str = "MiniMax-M2.7") -> tuple[str, list[dict]]:\n'
    '    """\n'
    '    Arts & Sciences tree retrieval — two steps:\n'
    '    1. Ask MiniMax to identify relevant section page ranges from the TOC.\n'
    '    2. Extract PDF text for those pages and answer.\n'
    '    """\n'
    '    from utils import get_text_of_pages\n'
    '\n'
    '    def build_section_index(nodes, depth=0, lines=None):\n'
    '        if lines is None:\n'
    '            lines = []\n'
    '        for node in nodes:\n'
    '            title = node.get("title", "")\n'
    '            start = node.get("start_index", 0)\n'
    '            end = node.get("end_index", start)\n'
    '            indent = "  " * depth\n'
    '            lines.append(f"{indent}[pages {start}-{end}] {title}")\n'
    '            if node.get("nodes"):\n'
    '                build_section_index(node["nodes"], depth + 1, lines)\n'
    '        return lines\n'
    '\n'
    '    section_index = "\\n".join(build_section_index(tree.get("structure", [])))\n'
    '\n'
    '    # Step 1: ask MiniMax which page ranges are relevant\n'
    '    select_prompt = (\n'
    '        "A student asks: \\"" + query + "\\"\\n\\n"\n'
    '        "Here is the table of contents for the Arts & Sciences section of the WashU Undergraduate Bulletin:\\n\\n"\n'
    '        + section_index + "\\n\\n"\n'
    '        "Which page range(s) are most relevant to answer this question? Return ONLY valid JSON:\\n"\n'
    '        "{\\n  \\"relevant_pages\\": [{\\n    \\"start\\": N, \\"end\\": M, \\"reason\\": \\"why relevant\\"\\n  }}]\\n}\\n\\n"\n'
    '        "Only return pages that are truly relevant. If nothing in the bulletin can answer, return {\\"relevant_pages\\": []}."\n'
    '    )\n'
    '\n'
    '    try:\n'
    '        raw = call_minimax(model=model, prompt=select_prompt)\n'
    '        parsed = json.loads(raw) if raw.startswith("{") else {}\n'
    '    except Exception:\n'
    '        parsed = {}\n'
    '\n'
    '    page_ranges = []\n'
    '    if isinstance(parsed, dict):\n'
    '        for item in parsed.get("relevant_pages", []):\n'
    '            start = int(item.get("start", 0))\n'
    '            end = int(item.get("end", start))\n'
    '            if start > 0:\n'
    '                page_ranges.append((start, end))\n'
    '\n'
    '    # Step 2: extract PDF text for the selected pages\n'
    '    sources = []\n'
    '    context_blocks = []\n'
    '    if page_ranges:\n'
    '        pdf_path = get_bulletin_pdf()\n'
    '        for start, end in page_ranges[:4]:\n'
    '            try:\n'
    '                text = get_text_of_pages(str(pdf_path), start, end, tag=False)\n'
    '                if text and len(text.strip()) > 50:\n'
    '                    snippet = text[:2000]\n'
    '                    context_blocks.append("[Pages " + str(start) + "-" + str(end) + "]\\n" + snippet)\n'
    '                    sources.append({\n'
    '                        "title": "Pages " + str(start) + "-" + str(end),\n'
    '                        "page_range": str(start) + "-" + str(end),\n'
    '                        "text": snippet[:500],\n'
    '                    })\n'
    '            except Exception:\n'
    '                pass\n'
    '\n'
    '    # Step 3: answer from context\n'
    '    if context_blocks:\n'
    '        context = "\\n\\n".join(context_blocks)\n'
    '        answer_prompt = (\n'
    '            "You are a WashU degree requirement assistant. A student asks: \\"" + query + "\\"\\n\\n"\n'
    '            "Here is relevant content from the WashU Undergraduate Bulletin:\\n\\n"\n'
    '            + context + "\\n\\n"\n'
    '            "Based ONLY on the content above, answer the student\\'s question. "\n'
    '            "Be specific with course numbers and unit counts. "\n'
    '            "If the answer is not in the content, say \\"I couldn\\'t find this information in the bulletin.\\""\n'
    '        )\n'
    '        try:\n'
    '            answer = call_minimax(model=model, prompt=answer_prompt)\n'
    '            answer = (answer or "").strip()\n'
    '            if not answer:\n'
    '                answer = "I couldn\\'t find a confident answer."\n'
    '        except Exception:\n'
    '            answer = "I couldn\\'t find a confident answer."\n'
    '    else:\n'
    '        answer = "I couldn\\'t find relevant sections in the bulletin for this question."\n'
    '\n'
    '    return answer, sources\n'
)

# Find the tree_retrieve function and replace it
pattern = r'def tree_retrieve\(query: str.*?(?=# ── Routes ───────────────────────────────────────────────────────────────────)'
new_content = re.sub(pattern, new_func.strip(), content, flags=re.DOTALL)

if new_content == content:
    print("ERROR: no replacement made")
else:
    with open(r'C:\Users\ethan\.openclaw\workspace\builds\washu-navigator\backend\main.py', 'w', encoding='utf-8') as f:
        f.write(new_content)
    print("SUCCESS")
