# Read main.py and replace tree_retrieve (lines 162-283) with new function

with open(r'C:\Users\ethan\.openclaw\workspace\builds\washu-navigator\backend\main.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Lines are 0-indexed; tree_retrieve starts at line 162 (index 161), Routes at 284 (index 283)
OLD_START = 161  # 0-indexed line 162
OLD_END = 283    # 0-indexed line 283 (inclusive)

# Verify we're replacing the right thing
assert 'def tree_retrieve' in lines[OLD_START], f"Line {OLD_START+1} doesn't have tree_retrieve"
assert '# --- Routes' in lines[OLD_END+1] or '# ── Routes' in lines[OLD_END+1], f"Line {OLD_END+2} isn't Routes section"
print(f"Replacing lines {OLD_START+1}-{OLD_END+1} ({OLD_END-OLD_START+1} lines)")

# The new function — built as a list of lines to avoid escaping issues
new_func_lines = [
    'def tree_retrieve(query: str, tree: dict, model: str = "MiniMax-M2.7") -> tuple[str, list[dict]]:\n',
    '    """\n',
    '    Arts & Sciences retrieval: use MiniMax to match query to section headings\n',
    '    in the tree text, extract matching content, answer.\n',
    '    """\n',
    '    import re\n',
    '\n',
    '    # Collect all section headings from the tree text\n',
    '    def collect_headings(nodes, heading_set=None):\n',
    '        if heading_set is None:\n',
    '            heading_set = set()\n',
    '        for node in nodes:\n',
    '            text = node.get("text") or ""\n',
    '            # Find markdown headings like ## Heading, ### Heading, etc.\n',
    '            for match in re.finditer(r"(?im)^#{1,6}\\s+([^\\n]+)", text):\n',
    '                h = match.group(1).strip()\n',
    '                if len(h) > 4:\n',
    '                    heading_set.add(h)\n',
    '            if node.get("nodes"):\n',
    '                collect_headings(node["nodes"], heading_set)\n',
    '        return heading_set\n',
    '\n',
    '    all_headings = collect_headings(tree.get("structure", []))\n',
    '    heading_list = sorted(all_headings)[:80]\n',
    '    heading_str = "\\n".join("- " + h for h in heading_list)\n',
    '\n',
    '    # Ask MiniMax which section headings match the query\n',
    '    select_prompt = (\n',
    '        "A student asks: " + query + "\\n\\n"\n',
    '        "Here are section headings from the WashU Arts & Sciences bulletin:\\n\\n"\n',
    '        + heading_str + "\\n\\n"\n',
    '        "Which heading(s) are most relevant? Return ONLY valid JSON with key \\'headings\\': [\\"heading1\\", ...]. "\n',
    '        "Return at most 3. If none match, return {\\"headings\\": []}."\n',
    '    )\n',
    '\n',
    '    try:\n',
    '        raw = call_minimax(model=model, prompt=select_prompt)\n',
    '        parsed = json.loads(raw) if raw.startswith("{") else {}\n',
    '    except Exception:\n',
    '        parsed = {}\n',
    '\n',
    '    selected = parsed.get("headings", []) if isinstance(parsed, dict) else []\n',
    '\n',
    '    # Find nodes whose text contains selected headings\n',
    '    def find_nodes_by_heading(nodes, targets, results=None):\n',
    '        if results is None:\n',
    '            results = []\n',
    '        for node in nodes:\n',
    '            text = node.get("text") or ""\n',
    '            title = node.get("title", "")\n',
    '            for h in targets:\n',
    '                if h.lower() in text.lower():\n',
    '                    results.append((title, text))\n',
    '                    break\n',
    '            if node.get("nodes"):\n',
    '                find_nodes_by_heading(node["nodes"], targets, results)\n',
    '        return results\n',
    '\n',
    '    matched = find_nodes_by_heading(tree.get("structure", []), selected)\n',
    '\n',
    '    # Keyword fallback\n',
    '    keywords = [k.strip() for k in query.split() if len(k.strip()) > 3]\n',
    '    kw_key = " ".join(keywords[:5])\n',
    '\n',
    '    def kw_search(nodes, kw_str, results=None):\n',
    '        if results is None:\n',
    '            results = []\n',
    '        for node in nodes:\n',
    '            text = (node.get("text") or "").lower()\n',
    '            title = (node.get("title") or "").lower()\n',
    '            score = sum(1 for kw in kw_str.split() if kw in title or kw in text)\n',
    '            if score >= 2 and len(node.get("text") or "") > 500:\n',
    '                results.append((score, node.get("title", ""), node.get("text", "")))\n',
    '            if node.get("nodes"):\n',
    '                kw_search(node["nodes"], kw_str, results)\n',
    '        return results\n',
    '\n',
    '    kw_matches = kw_search(tree.get("structure", []), kw_key.lower())\n',
    '    kw_matches.sort(key=lambda x: -x[0])\n',
    '\n',
    '    # Build context from heading matches, then keyword matches\n',
    '    context_blocks = []\n',
    '    sources = []\n',
    '    seen = set()\n',
    '\n',
    '    for title, text in matched:\n',
    '        if title not in seen and len(text) > 200:\n',
    '            seen.add(title)\n',
    '            snippet = text[:5000]\n',
    '            context_blocks.append("[" + title + "]\\n" + snippet)\n',
    '            sources.append({"title": title, "page_range": "", "text": snippet[:500]})\n',
    '\n',
    '    for score, title, text in kw_matches:\n',
    '        if title not in seen and len(text) > 200 and len(context_blocks) < 4:\n',
    '            seen.add(title)\n',
    '            snippet = text[:3000]\n',
    '            context_blocks.append("[" + title + "]\\n" + snippet)\n',
    '            sources.append({"title": title, "page_range": "", "text": snippet[:500]})\n',
    '\n',
    '    if not context_blocks:\n',
    '        return "I couldn\'t find relevant sections in the bulletin for this question.", []\n',
    '\n',
    '    context = "\\n\\n".join(context_blocks)\n',
    '\n',
    '    answer_prompt = (\n',
    '        "You are a WashU degree requirement assistant. A student asks: " + query + "\\n\\n"\n',
    '        "Here is relevant content from the WashU Undergraduate Bulletin:\\n\\n"\n',
    '        + context + "\\n\\n"\n',
    '        "Based ONLY on the content above, answer the student\'s question. "\n',
    '        "Be specific with course numbers and unit counts. "\n',
    '        "If the answer is not in the content, say I couldn\'t find this information."\n',
    '    )\n',
    '\n',
    '    try:\n',
    '        answer = call_minimax(model=model, prompt=answer_prompt)\n',
    '        answer = (answer or "").strip()\n',
    '        if not answer:\n',
    '            answer = "I couldn\'t find a confident answer."\n',
    '    except Exception:\n',
    '        answer = "I couldn\'t find a confident answer."\n',
    '\n',
    '    return answer, sources\n',
    '\n',
]

new_lines = lines[:OLD_START] + new_func_lines + lines[OLD_END+1:]
with open(r'C:\Users\ethan\.openclaw\workspace\builds\washu-navigator\backend\main.py', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print(f"Done! New file has {len(new_lines)} lines")
